---
language: python

before_install:
    # Make sure everything's up to date.
    - sudo apt-get update -qq
install:
    # Install Ansible
    - pip install ansible
script:
    - rm -rf ~/.gitconfig
    - rm -rf ~/.zshrc
    - rm -rf ~/.bash_profile
    - git clone https://github.com/miholeus/dotfiles.git /var/tmp/dotfiles
    - cp host_vars/{127.0.0.1.dist,127.0.0.1}
    - make
