---
- hosts: all
  tasks:
      - file: src={{ curdir }}/files/{{ item }} dest=~/.{{ item }} state=link
        with_items:
            - bash_aliases
            - bash_profile
              #- gitconfig
              #- hgrc
            - vimrc
            - zshrc
