---
- hosts: all
  tasks:
      - file: src={{ curdir }}/files/{{ item }} dest=~/.{{ item }} state=link
        with_items:
            - bash_aliases
            - bash_profile
            - vimrc
            - zshrc
      - name: Install Mercurial config
        template: src=files/hgrc dest=~/.hgrc
      - name: Install Git config
        template: src=files/gitconfig dest=~/.gitconfig
      - name: Add completions directory
        file: path=~/.zsh/completions state=directory mode=0755
      - name: Install github completion
        template: src=files/completions/hub.zsh_completion dest=~/.zsh/completions/_hub
      - name: Curl format
        template: src=files/curl-format.txt dest=~/.curl-format.txt
