---
- hosts: all
  tasks:
      - file: src={{ curdir }}/files/{{ item }} dest=~/.{{ item }} state=link
        with_items:
            - bash_aliases
            - bash_profile
            - vimrc
            - zshrc
      - name: Install Mercurial config
        template: src=files/hgrc dest=~/.hgrc
      - name: Install Git config
        template: src=files/gitconfig dest=~/.gitconfig