PHP_AUTOCONF="/usr/local/bin/autoconf"
source ~/.bash_aliases

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

source ~/.profile
source /usr/local/bin/virtualenvwrapper.sh
